version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: esc_c3t2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres-test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: esc_c3t2_test
    ports:
      - "5433:5432" # Host port: Container port, Postgres always uses 5432 internally
    volumes:
      - postgres_test_data:/var/lib/postgresql/data # Seperate volume for test database

volumes:
  postgres_data:
  postgres_test_data:
