CREATE TABLE caregivers (
	id TEXT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	phone VARCHAR(15),
	address TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);